import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({ subsets: ['latin'] })

export const metadata = {
  title: 'Petrus Borges',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}
